version: '3.4'

services:
  drreview.api:
    build:
      context: .
      dockerfile: DrReview.Core/DrReview.Api/Dockerfile
    ports:
        - "4300:80"
        - "4400:443"
    depends_on:
            - drreview_hangfire_db
  drreview_hangfire_db:
      image: "mcr.microsoft.com/mssql/server:2019-latest"
      environment:
       ACCEPT_EULA: "Y"
       MSSQL_SA_PASSWORD: "Password!123"
      ports:
        - "1440:1433" 
